//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antix.Mail.Smtp.Impostor.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Antix.Mail.Smtp.Impostor.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close_Title {
            get {
                return ResourceManager.GetString("Close_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        internal static string Connected_Message {
            get {
                return ResourceManager.GetString("Connected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed communication with {0}.
        /// </summary>
        internal static string Disconnected_Message {
            get {
                return ResourceManager.GetString("Disconnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Host.
        /// </summary>
        internal static string Host_Create {
            get {
                return ResourceManager.GetString("Host_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started host {0} on {1} port {2}.
        /// </summary>
        internal static string Host_Started_Message {
            get {
                return ResourceManager.GetString("Host_Started_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped host {0} on {1} port {2}.
        /// </summary>
        internal static string Host_Stopped_Message {
            get {
                return ResourceManager.GetString("Host_Stopped_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP is invalid.
        /// </summary>
        internal static string IP_Invalid_Message {
            get {
                return ResourceManager.GetString("IP_Invalid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another service is on this IP and Port.
        /// </summary>
        internal static string IPPort_Taken_Message {
            get {
                return ResourceManager.GetString("IPPort_Taken_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write to event log.
        /// </summary>
        internal static string Log_Failed_Exception {
            get {
                return ResourceManager.GetString("Log_Failed_Exception", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon LogoIcon {
            get {
                object obj = ResourceManager.GetObject("LogoIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of messages.
        /// </summary>
        internal static string MessageCount_Title {
            get {
                return ResourceManager.GetString("MessageCount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message recieved from {0}.
        /// </summary>
        internal static string MessageReceived_Message {
            get {
                return ResourceManager.GetString("MessageReceived_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Received.
        /// </summary>
        internal static string MessageReceived_Title {
            get {
                return ResourceManager.GetString("MessageReceived_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started, check no other service is running on this address and port.
        /// </summary>
        internal static string NotStarted_Exception {
            get {
                return ResourceManager.GetString("NotStarted_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port is invalid.
        /// </summary>
        internal static string Port_Invalid_Message {
            get {
                return ResourceManager.GetString("Port_Invalid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings ....
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more host has failed to start, please check the configuration.
        /// </summary>
        internal static string Start_Failure_Message {
            get {
                return ResourceManager.GetString("Start_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostor started.
        /// </summary>
        internal static string Start_Success_Message {
            get {
                return ResourceManager.GetString("Start_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Started_Message {
            get {
                return ResourceManager.GetString("Started_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Stopped_Message {
            get {
                return ResourceManager.GetString("Stopped_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antix Impostor.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred, please check the event log for details.
        /// </summary>
        internal static string Unexpected_Exception {
            get {
                return ResourceManager.GetString("Unexpected_Exception", resourceCulture);
            }
        }
    }
}
