//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antix.Mail.Smtp.Impostor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /valueString option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Antix.Mail.Smtp.Impostor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not implemented.
        /// </summary>
        internal static string CommandNotImplemented_502 {
            get {
                return ResourceManager.GetString("CommandNotImplemented_502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command out of sequence.
        /// </summary>
        internal static string CommandSequenceError_503 {
            get {
                return ResourceManager.GetString("CommandSequenceError_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Completed_250 {
            get {
                return ResourceManager.GetString("Completed_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected HELO &lt;Your Name&gt;.
        /// </summary>
        internal static string ExpectedHELO_503 {
            get {
                return ResourceManager.GetString("ExpectedHELO_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good bye.
        /// </summary>
        internal static string Goodbye_250 {
            get {
                return ResourceManager.GetString("Goodbye_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}.
        /// </summary>
        internal static string Hello_250 {
            get {
                return ResourceManager.GetString("Hello_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}, Antix SMTP Impostor.
        /// </summary>
        internal static string Ready_220 {
            get {
                return ResourceManager.GetString("Ready_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Data, end with &lt;CRLF&gt;.&lt;CRLF&gt;.
        /// </summary>
        internal static string StartInput_354 {
            get {
                return ResourceManager.GetString("StartInput_354", resourceCulture);
            }
        }
    }
}
